apiVersion: galbimandudev.com/v1alpha1
kind: Mysql
metadata:
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: mysql-sample
    app.kubernetes.io/part-of: mysql-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: mysql-operator
  name: mysql-sample
spec:
  # TODO(user): Add fields here
  dataPvcName: test-pvc-name
  image: mysql:8.0.33
  replicas: 2
  rootPassword: "hello123"
  livenessProbe:
    exec:
      command:
        - bash
        - "-c"
        - echo  "Hello World"
    initialDelaySeconds: 60
    timeoutSeconds: 10
  readinessProbe:
    exec:
      command:
        - bash
        - "-c"
        - echo  "Hello World"
    initialDelaySeconds: 60
    timeoutSeconds: 10
